// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using nutriclinica_backend.Infrastructure.Persistence;

#nullable disable

namespace nutriclinica_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("nutriclinica_backend.Core.Entities.Cita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MotivoCancelacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("NutricionistaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FechaInicio");

                    b.HasIndex("NutricionistaId");

                    b.HasIndex("PacienteId", "FechaInicio");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("nutriclinica_backend.Core.Entities.Consulta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CitaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotasClinicas")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("NutricionistaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoConsulta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CitaId")
                        .IsUnique();

                    b.HasIndex("NutricionistaId");

                    b.HasIndex("PacienteId", "FechaInicio");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("nutriclinica_backend.Core.Entities.DocumentoPaciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConsultaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("PacienteId");

                    b.ToTable("DocumentosPaciente");
                });

            modelBuilder.Entity("nutriclinica_backend.Core.Entities.FotoSeguimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConsultaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlFoto")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("PacienteId");

                    b.ToTable("FotosSeguimiento");
                });

            modelBuilder.Entity("nutriclinica_backend.Core.Entities.HistorialClinico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("Alergias")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("AlimentosFavoritos")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("AlimentosNoFavoritos")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId")
                        .IsUnique();

                    b.ToTable("HistorialesClinicos");
                });

            modelBuilder.Entity("nutriclinica_backend.Core.Entities.MedidaAntropometrica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConsultaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Estatura")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("FechaMedicion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Imc")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<decimal?>("MedidaCadera")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("MedidaCintura")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("NotasObservaciones")
                        .HasColumnType("text");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Peso")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("PorcentajeGrasa")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<decimal?>("PorcentajeMasaMuscular")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("PacienteId");

                    b.ToTable("MedidasAntropometricas");
                });

            modelBuilder.Entity("nutriclinica_backend.Core.Entities.Nutricionista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroColegiatura")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CorreoElectronico")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("NumeroColegiatura")
                        .IsUnique();

                    b.ToTable("Nutricionistas");
                });

            modelBuilder.Entity("nutriclinica_backend.Core.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PesoObjetivo")
                        .HasColumnType("numeric");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TituloObjetivo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pacientes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pacientes_Sexo", "\"Sexo\" IN ('M','F','Otro')");
                        });
                });

            modelBuilder.Entity("nutriclinica_backend.Core.Entities.Cita", b =>
                {
                    b.HasOne("nutriclinica_backend.Core.Entities.Nutricionista", "Nutricionista")
                        .WithMany("Citas")
                        .HasForeignKey("NutricionistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("nutriclinica_backend.Core.Entities.Paciente", "Paciente")
                        .WithMany("Citas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nutricionista");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("nutriclinica_backend.Core.Entities.Consulta", b =>
                {
                    b.HasOne("nutriclinica_backend.Core.Entities.Cita", "Cita")
                        .WithOne("Consulta")
                        .HasForeignKey("nutriclinica_backend.Core.Entities.Consulta", "CitaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("nutriclinica_backend.Core.Entities.Nutricionista", "Nutricionista")
                        .WithMany("Consultas")
                        .HasForeignKey("NutricionistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("nutriclinica_backend.Core.Entities.Paciente", "Paciente")
                        .WithMany("Consultas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("Nutricionista");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("nutriclinica_backend.Core.Entities.DocumentoPaciente", b =>
                {
                    b.HasOne("nutriclinica_backend.Core.Entities.Consulta", "Consulta")
                        .WithMany()
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("nutriclinica_backend.Core.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("nutriclinica_backend.Core.Entities.FotoSeguimiento", b =>
                {
                    b.HasOne("nutriclinica_backend.Core.Entities.Consulta", "Consulta")
                        .WithMany()
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("nutriclinica_backend.Core.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("nutriclinica_backend.Core.Entities.HistorialClinico", b =>
                {
                    b.HasOne("nutriclinica_backend.Core.Entities.Paciente", "Paciente")
                        .WithOne("HistorialClinico")
                        .HasForeignKey("nutriclinica_backend.Core.Entities.HistorialClinico", "PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("nutriclinica_backend.Core.Entities.MedidaAntropometrica", b =>
                {
                    b.HasOne("nutriclinica_backend.Core.Entities.Consulta", "Consulta")
                        .WithMany()
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("nutriclinica_backend.Core.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("nutriclinica_backend.Core.Entities.Cita", b =>
                {
                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("nutriclinica_backend.Core.Entities.Nutricionista", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Consultas");
                });

            modelBuilder.Entity("nutriclinica_backend.Core.Entities.Paciente", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Consultas");

                    b.Navigation("HistorialClinico");
                });
#pragma warning restore 612, 618
        }
    }
}
